version: '3'
volumes:
  runner-root-cache: {}
services:
  ms:
    restart: always
    image: apt-mirror
    privileged: true
    volumes:
      - runner-root-cache:/root
      - ./mirror-data:/var/spool/apt-mirror:rw
      ###########################secrets
      - ./secrets/tunasync/: /home/ts/.config/tunasync
  nginx:
    restart: always
    image: apt-mirror
    ports:
      - "80:80"
      - "443:443"
    command: ["nginx"]
    volumes:
      - ./mirror-data:/var/spool/apt-mirror:ro
      ###########################secrets   
      - ./secrets/nginx/:/etc/nginx/conf.d/

